### PR TITLE
Authorgroup controller

### PR DESCRIPTION
**Pull request by mingxuan-fu**

### CODE REVIEW

**Comment by mingxuan-fu** [comment]
Author Group creation
image

List all Author Groups
image

Get one Author Group
image

Author Group from user API
image

**Review by Linh-Doan — COMMENTED** [review]
Mostly look pretty good, though I have 2 suggestions:
- With creating a new group, group ID should be auto generated rather then providing it.
- Get user should be done by id. If you want to have the option to get by email, use a query parameter instead

**Comment by mingxuan-fu** [comment]
image
Added query params for emails

**Review by Linh-Doan — COMMENTED** [review]
Could you also make the author_group_id being auto generated rather than having to be provided in the query?

**Review by Linh-Doan — APPROVED** [review]

**Pull request merged**
