### PR TITLE
chapter controllers

### PR DESCRIPTION
**Pull request by echooff16**
Populated the data for the chapter and linked the book ID with the new book ID.
Tested with Postman.

### CODE REVIEW

**Review by Linh-Doan — COMMENTED** [review]
Could you please add the screenshots of the postman calls?
And another comment is when a post request is sent, the request should not have to contain the id. Chapter_id should be auto generated by the DB. You can check out the ddl code for book or genre in init.sql and prisma.schema to see what I mean

**Comment by echooff16** [comment]
image
Screenshot^^

Fixed chapter id thingy

**Comment by echooff16** [comment]
image

Fixed dynamic chapter id (just like book id and genre)

**Review by Linh-Doan — APPROVED** [review]

**Pull request merged**
